name: make-master
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup DEVKITPRO
        run: |
          # 安装依赖
          sudo apt update
          sudo apt install -y libssl-dev
          # 下载最新的 devkitPro 安装脚本
          #wget -qO- https://devkitpro.org/updates/devkitpro.sh | bash
          wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
          RUN dpkg -i devkitpro-pacman.deb && dkp-pacman -S switch-dev --noconfirm
          RUN source /etc/profile.d/devkit-env.sh
   
          # 设置环境变量
          echo "export DEVKITPRO=$(pwd)/devkitpro" >> $GITHUB_ENV
          echo "export DEVKITARMPRO=$(pwd)/devkitpro/devkitARMpro" >> $GITHUB_ENV
          echo "export PATH=$PATH:$DEVKITPRO/tools/bin:$DEVKITPRO/tools/arm-none-eabi/bin" >> $GITHUB_ENV
   
          # 验证安装
          #ctrulib_tool --version
      - name: Run Makefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make all
      - name: 打包应用程序
        run: |
          find . -name '*.nro' | xargs zip -r app.zip
        working-directory: ./
  
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app.zip
