name: make-master
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup DEVKITPRO
        run: |
          # 安装依赖
          sudo apt update
          sudo apt install -y libssl-dev
          # 下载最新的 devkitPro 安装脚本
          #wget -qO- https://devkitpro.org/updates/devkitpro.sh | bash
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
   
          # 设置环境变量
          echo "export DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "export DEVKITARMPRO=/opt/devkitpro/devkitARMpro" >> $GITHUB_ENV
          echo "export PATH=$PATH:$DEVKITPRO/tools/bin:$DEVKITPRO/tools/arm-none-eabi/bin" >> $GITHUB_ENV
   
          # 验证安装
          #ctrulib_tool --version
      - name: Run Makefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DEVKITPRO: /opt/devkitpro
        run: |
          export DEVKITPRO=/opt/devkitpro
          make all
      - name: 打包应用程序
        run: |
          find . -name '*.nro' | xargs zip -r app.zip
        working-directory: ./
  
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app.zip
